name: run

on: 
  push:
  workflow_dispatch:
  schedule:
      - cron: "0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * *"
    
jobs:
  run_sign:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Run sign
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SECRET:  ${{ secrets.SECRET }}
        RUN_TIME: "1"
        LATITUDE:  ${{ secrets.LATITUDE }}
        LONGITUDE: ${{ secrets.LONGITUDE }}
      run: |
        python3 local_sign.py
